wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: ${default_gateway}
    subnet: ${subnet}

web_server:
  port: 80

captive_portal:


# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

time:
  - platform: homeassistant
    id: my_time

