substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: bedroom-midea-fan-coil
  friendly_name: Bedroom Midea Fan Coil
  icon: mdi:hvac
  ip_address: 192.168.100.62
  default_gateway: 192.168.100.1
  subnet: 255.255.255.0

<<: !include .common.yaml
<<: !include .esp32-c3-midea-mkg-fan-coil.yaml
